import React from "react";
import Head from "next/head";
import { brand } from "../../lib/data/brand";

export function Header() {
  return (
    <Head>
      <title>{brand.name}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
