import React from "react";
import Head from "next/head";
import { brand } from "../../lib/data/brand";

export function Header({ title }: { title: string }) {
    return (
        <Head>
            <title>
                {title
                    ? `${title}${" | "}${brand.name} app`
                    : `${brand.name} app`}
            </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}
